# Generated by Django 5.1.5 on 2025-02-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaApp', '0002_topping_remove_pizza_toppings_pizza_toppings'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='cheese',
            field=models.CharField(choices=[('Mozzarella', 'Mozzarella'), ('Cheddar', 'Cheddar'), ('Parmesan', 'Parmesan'), ('Vegan', 'Vegan Cheese'), ('Low', 'Low fat Cheese')], default='Mozzarella', max_length=20),
        ),
        migrations.AddField(
            model_name='pizza',
            name='crust',
            field=models.CharField(choices=[('Thin', 'Thin Crust'), ('Thick', 'Thick Crust'), ('Stuffed', 'Stuffed Crust'), ('Gluten-Free', 'Gluten-Free')], default='Thin', max_length=20),
        ),
        migrations.AddField(
            model_name='pizza',
            name='sauce',
            field=models.CharField(choices=[('Tomato', 'Tomato Sauce'), ('BBQ', 'BBQ Sauce'), ('Alfredo', 'Alfredo Sauce'), ('Pesto', 'Pesto Sauce')], default='Tomato', max_length=20),
        ),
    ]
