# Generated by Django 5.1.5 on 2025-02-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaApp', '0004_cheese_crust_sauce_size_alter_pizza_cheese_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='cheese',
            field=models.CharField(choices=[('Mozzarella', 'Mozzarella'), ('Cheddar', 'Cheddar'), ('Parmesan', 'Parmesan'), ('Vegan', 'Vegan Cheese')], default='Mozzarella', max_length=20),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='crust',
            field=models.CharField(choices=[('Thin', 'Thin Crust'), ('Thick', 'Thick Crust'), ('Stuffed', 'Stuffed Crust'), ('Gluten-Free', 'Gluten-Free')], default='Thin', max_length=20),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='sauce',
            field=models.CharField(choices=[('Tomato', 'Tomato Sauce'), ('BBQ', 'BBQ Sauce'), ('Alfredo', 'Alfredo Sauce'), ('Pesto', 'Pesto Sauce')], default='Tomato', max_length=20),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Cheese',
        ),
        migrations.DeleteModel(
            name='Crust',
        ),
        migrations.DeleteModel(
            name='Sauce',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
