# Generated by Django 5.1.5 on 2025-02-04 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaApp', '0005_alter_pizza_cheese_alter_pizza_crust_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Crust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sauce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pizza',
            name='cheese',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzaApp.cheese'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='crust',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzaApp.crust'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='sauce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzaApp.sauce'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzaApp.size'),
        ),
    ]
