# Generated by Django 5.1.5 on 2025-02-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaApp', '0007_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
