# Generated by Django 5.1.5 on 2025-02-06 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaApp', '0008_payment_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
