# Generated by Django 5.1.5 on 2025-02-06 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaApp', '0010_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='card_cvv',
            new_name='cvv',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='card_expiry',
            new_name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='city',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='pizza',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pizzaApp.pizza'),
            preserve_default=False,
        ),
    ]
